# AI Short-Video Creator - Docker Compose Configuration
version: '3.8'

services:
  ai-video-creator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ai-video-creator
    ports:
      - "8501:8501"
    volumes:
      # Mount for persistent model storage
      - model_cache:/app/models
      # Mount for output files
      - video_outputs:/app/assets/outputs
      # Optional: Mount for custom assets
      - ./assets:/app/assets/custom:ro
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      # Optional API keys (set in .env file)
      - PEXELS_API_KEY=${PEXELS_API_KEY:-}
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN:-}
    restart: unless-stopped
    mem_limit: 8g
    mem_reservation: 4g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai-video-creator.rule=Host(`your-domain.com`)"
      - "traefik.http.services.ai-video-creator.loadbalancer.server.port=8501"

  # Optional: Add GPU support (uncomment for NVIDIA GPU)
  # ai-video-creator-gpu:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile.gpu
  #   container_name: ai-video-creator-gpu
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - model_cache:/app/models
  #     - video_outputs:/app/assets/outputs
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - PYTHONUNBUFFERED=1
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   restart: unless-stopped

  # Optional: Redis for caching (for production)
  # redis:
  #   image: redis:7-alpine
  #   container_name: ai-video-creator-cache
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

volumes:
  model_cache:
    driver: local
  video_outputs:
    driver: local
  # redis_data:
  #   driver: local

networks:
  default:
    name: ai-video-creator-network